Hooks.once("ready", async function () {
  if (game.modules.get("pf1-statblock-converter")?.active) {
    if (game.modules.get("pf1-statblock-converter").version.startsWith("5")) return;

    Hooks.on("sbc.loadCustomCompendiums", function (packs) {
      packs.push(
        ...[
          "pf-content.pf-35-content",
          "pf-content.pf-artifacts",
          "pf-content.pf-buffs",
          "pf-content.pf-collab-content",
          "pf-content.pf-class-abilities",
          "pf-content.pf-companion-features",
          "pf-content.pf-cursed-items",
          "pf-content.pf-eidolon-evolutions",
          "pf-content.pf-elephant",
          "pf-content.pf-feats",
          "pf-content.pf-goods-services",
          "pf-content.pf-items",
          "pf-content.pf-magicitems",
          "pf-content.pf-maladies",
          "pf-content.pf-occult-rituals",
          "pf-content.pf-racial-traits",
          "pf-content.pf-special-qualities",
          "pf-content.pf-traits",
          "pf-content.pf-universal-monster-rules",
          "pf-content.pf-wondrous",
        ]
      );
    });
  }
});

Hooks.once("init", function () {
  const compendiumRenames = /** @type {const}*/ ({
    "pf-elephant": "pf-3rd-party",
    "pf-magic": "pf-magic-items",
  });

  const prefix = `Compendium.pf-content`;
  for (const [oldName, newName] of Object.entries(compendiumRenames)) {
    CONFIG.compendium.uuidRedirects[`${prefix}.${oldName}`] = `${prefix}.${newName}`;
  }
});

Hooks.on("pf1RegisterSources", (registry, _model) => {
  const sourceChanges = {
    FGG32698: {
      name: "Rappan Athuk",
      date: "2012",
      isbn: "978-1-62283-002-2",
      pages: 667,
      publisher: "Frog God Games",
      type: "module",
      url: "https://www.froggodgames.com/products/32698?variant=42700040732841",
    },
    FGG17316: {
      name: "Sword of Air",
      date: "2015",
      isbn: "978-1-62283-216-3",
      pages: 522,
      publisher: "Frog God Games",
      type: "module",
      url: "https://www.froggodgames.com/products/17316",
    },
    FGGWWP08366E: {
      name: "Rappan Athuk-New Encounters",
      date: "2006",
      isbn: "1-58846-795-3",
      pages: 384,
      publisher: "White Wolf Publishing",
      type: "module",
      url: "https://www.froggodgames.com/products/1488",
    },
    FGGTLGNGB2E: {
      name: "The Lost City of Barakus",
      date: "2014",
      isbn: "978-1-62283-207-1",
      pages: 174,
      publisher: "Frog God Games",
      type: "module",
      url: "https://paizo.com/products/btpy92np?The-Lost-City-of-Barakus",
    },
    PZOGWK0001: {
      name: "Thornkeep",
      date: "2013-01",
      isbn: "978-1-60125-519-8",
      pages: 96,
      publisher: "Paizo and Goblinworks",
      type: "module",
      url: "https://paizo.com/products/btpy8tb0",
    },
    "PZO9000-S": {
      name: "Rise of the Runelords Player's Guide",
      date: "2007-08",
      isbn: "978-1-60125-059-9",
      pages: 16,
      publisher: "Paizo",
      type: "ap",
      url: "https://paizo.com/products/btpy8bd9",
    },
    PZO90118: {
      name: "Ironfang Invasion #4: Siege of Stone",
      date: "2017-05-24",
      isbn: "978-1-60125-940-0",
      pages: 96,
      publisher: "Paizo",
      type: "ap",
      url: "https://paizo.com/products/btpy9pn4",
    },
    PZOPSS0054E: {
      name: "PFS S1-54: The Maze of the Open Road",
      date: "2010-06",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8dal",
    },
    PZOPSS0206E: {
      name: "PFS S2-06: The First Heresy",
      date: "2010-09",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8g1s",
    },
    PZOPSS0209E: {
      name: "PFS S2-09: Beneath Forgotten Sands",
      date: "2010-11",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8g1v",
    },
    PZOPSS0222E: {
      name: "PFS S2-22: Nothing Ventured, Nothing Gained",
      date: "2011-05",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8gtt",
    },
    PZOPSS0225E: {
      name: "PFS S2-25: You Only Die Twice",
      date: "2011-06",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8jop",
    },
    "PZOPSS0200-1": {
      name: "PFS S2-Special: Year of the Shadow Lodge",
      date: "2010-08",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8g6e",
    },
    PZOPSS0312E: {
      name: "PFS S3-12: The Dog Pharaoh's Tomb",
      date: "2011-12",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8ow2",
    },
    PZOPSS0313E: {
      name: "PFS S3-13: Defenders of Nesting Swallow",
      date: "2012-01",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8ow3",
    },
    PZOPSS0316: {
      name: "PFS S3-16: The Midnight Mauler",
      date: "2012-02",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8qpv",
    },
    PZOPSS0325: {
      name: "PFS S3-25: Storming the Diamond Gate",
      date: "2012-07",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8r0a",
    },
    PZOPSS0401: {
      name: "PFS S4-01: Rise of the Goblin Guild",
      date: "2012-08",
      pages: 25,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8r0e",
    },
    PZOPSS0406: {
      name: "PFS S4-06: The Green Market",
      date: "2012-09",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8u8s",
    },
    PZOPSS0408: {
      name: "PFS S4-08: The Cultist's Kiss",
      date: "2012-10",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8u8u",
    },
    PZOPSS0412: {
      name: "PFS S4-12: The Refuge of Time",
      date: "2012-12",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8v0i",
    },
    PZOPSS0419E: {
      name: "PFS S4-19: The Night March of Kalkamedes",
      date: "2013-04",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8wdz",
    },
    PZOPSS0420E: {
      name: "PFS S4-20: Words of the Ancients",
      date: "2013-04",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8we0",
    },
    PZOPSS0426E: {
      name: "PFS S4-26: The Waking Rune",
      date: "2013-07",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy8we6",
    },
    PZOPSS0513E: {
      name: "PFS S5-13: Weapon in the Rift",
      date: "2014-01",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy93m1",
    },
    PZOPSS0514E: {
      name: "PFS S5-13: Day of the Demon",
      date: "2014-02",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy93m2",
    },
    PZOPSS0516E: {
      name: "PFS S5-16: Sanctum of the Sages",
      date: "2014-03",
      pages: 31,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy93m4",
    },
    PZOPSS0517E: {
      name: "PFS S5-17: Fate of the Fiend",
      date: "2014-03",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy93m5",
    },
    PZOPSS0609: {
      name: "PFS S6-09: By Way of Bloodcove",
      date: "2014-11-26",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy9a1x",
    },
    PZOPSS0611: {
      name: "PFS S6-11: The Slave Master's Mirror",
      date: "2014-12-31",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy9a1z",
    },
    PZOPSS0616: {
      name: "PFS S6-16: The Golden Guardian",
      date: "2015-03-25",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy9am7",
    },
    PZOPSS0802E: {
      name: "PFS S8-02: Ward Asunder",
      date: "2016-08-04",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy9mbb",
    },
    PZOPSS0803E: {
      name: "PFS S8-03: Captives of Toil",
      date: "2016-08-04",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy9mbc",
    },
    PZOPSS0806E: {
      name: "PFS S8-06: Reaping What We Sow",
      date: "2016-10-26",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy9oij",
    },
    PZOPSS0810E: {
      name: "PFS S8-10: Secrets of the Endless Sky",
      date: "2016-12-21",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy9p8x",
    },
    PZOPSS0812E: {
      name: "PFS S8-12: Caught in the Eclipse",
      date: "2017-01-25",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy9p8z",
    },
    PZOPSS0815E: {
      name: "PFS S8-15: Hrethnar's Throne",
      date: "2017-02-22",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy9qca",
    },
    PZOPSS0825E: {
      name: "PFS S8-25: Unleashing the Untouchable",
      date: "2017-07-26",
      pages: 24,
      publisher: "Paizo",
      type: "pfs",
      url: "https://paizo.com/products/btpy9tl9",
    },
  };

  for (const [sourceId, sourceData] of Object.entries(sourceChanges)) {
    registry.register("pf-content", sourceId, sourceData);
  }
});
